# Generated by Django 5.0.6 on 2024-11-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_cart_is_paid_orders_payment_gateway_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cancelled_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
